Wait for Elasticsearch until a connection can be made on startup with version probe enabled
Graylog2/documentation pull request #1153
Opened 2021-06-02 20:06 UTC by janheise

Added documentation fort the new configuration options for Elasticsearch to configure the behavior with version probing enabled. Also added the changed behavior the the Upgrade doc

2021-06-08 08:09 UTC, dennisoelkers requested changes
Looks good, one minor remark.

2021-06-08 08:09 UTC, dennisoelkers commented on pages/upgrade/graylog-4.1.rst
> +When you have version-probing for the used Elasticsearch version enabled, and Graylog starts up but can not connect to ES, the startup stopped immediately with v4.0 and prior. Starting from 4.1 the d
This is slightly inaccurate. Before v4.0, there was no version probing, but prior to v4.0 _and_ in v4.0 _without_ version probing, Graylog continues connecting to ES until it is successfull, so this change is a breaking change compared to v4.0, but makes the behavior consistent with versions v3.3 and before _and_ with the behavior when version probing is disabled.

2021-06-18 08:32 UTC, bernd commented
@janheise Can you resolve the conflicts and address @dennisoelkers comment so we can merge this for 4.1? Thank you! :slightly_smiling_face:

2021-06-23 14:16 UTC, dennisoelkers approved these changes
Looks good! :tada:

2021-06-23 14:16 UTC, merged