Add Metrics page with Prometheus Exporter section
Graylog2/documentation pull request #1166
Opened 2021-06-17 21:49 UTC by danotorrey

Add documentation for the new core open-source Prometheus Exporter feature. 

We did not yet have a main page, which discusses Graylog metrics, so I have added a new top-level page titled `Metrics`. A general description of standard Graylog metrics at the top as a prelude to discussing Prometheus exports in detail.

Closes #1154

2021-06-17 22:38 UTC, danotorrey commented
@bernd @dulanism Since this will be included in the 4.1 release, and some customers are wanting to utilize it, I wanted to add some docs for it.

If you can find the time to do an initial review of this tomorrow (Friday) or Monday morning, that would be really helpful. I would like to try and merge this on Monday so that it will be ready to go on release day.

2021-06-18 07:41 UTC, bernd requested changes
Thank you! :pray: Only one comment and one question:

2021-06-18 07:41 UTC, bernd commented on pages/metrics.rst
> +Depending on the current Prometheus `scrape_config setting <https://eus.io/docs/prometheus/latest/configuration/configuration/#scrape_config>`_,
The link has been truncated:

```suggestion
Depending on the current Prometheus `scrape_config setting <https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config>`_,
```

2021-06-18 07:41 UTC, bernd commented on pages/metrics.rst
> +the Graylog Prometheus exporter may be discovered automatically, or an explicit scrape target might need to be
How would the exporter be discovered automatically? Is there a way to do that? :slightly_smiling_face:

2021-06-18 14:25 UTC, danotorrey commented on pages/metrics.rst
> +the Graylog Prometheus exporter may be discovered automatically, or an explicit scrape target might need to be
Thanks for seeing this. From a second-look, I think I misunderstood how the automatic discovery works. It looks like this is only supported in some special configurations (such as [Kubernetes setups](https://developer.sh/posts/prometheus-self-discovery)) where the list of cluster host names is already known through other means. It's not really applicable for the purposes of this docs page. 

I have re-worded this section to be a bit more general and not reference auto-discovery.

2021-06-21 17:02 UTC, bernd approved these changes

2021-06-21 18:28 UTC, merged