faq.rst: fix /etc/default/, SMTP CA truststore instructions
Graylog2/documentation pull request #220
Opened 2016-10-26 16:54 UTC by mchubby

2016-10-26 16:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Graylog2/documentation?pullRequest=220) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Graylog2/documentation?pullRequest=220) before we can accept your contribution.<br/>

2016-10-27 07:09 UTC, joschi requested changes
@mchubby Thank you very much!

Except for the syntax issue with the hyperlink reference, this looks good to me.

2016-10-27 07:09 UTC, joschi commented on pages/faq.rst
> +Fedora/RHEL-based systems may refer to the `Fedora wiki article <https://fedoraproject.org/wiki/Features/SharedSystemCertificates>`
Missing trailing underscore for the link reference, see http://www.sphinx-doc.org/en/stable/rest.html#hyperlinks

2016-10-27 15:10 UTC, mchubby commented
Thanks, done. I don't know how to squash the commits from the web ui, though. There should be a green button for squashing on the PR itself, though.

2016-10-27 15:45 UTC, joschi approved these changes

2016-10-27 15:45 UTC, merged

2016-10-27 15:45 UTC, joschi commented
@mchubby Thanks!