updated Step-by-step guides
Graylog2/documentation pull request #229
Opened 2016-11-28 11:15 UTC by jalogisch

after we got feedback via Mail just a few updates on thie guides

2016-12-09 17:41 UTC, bernd requested changes

2016-12-09 17:41 UTC, bernd commented on pages/installation/os/centos.rst
> +The next step is it :ref:`ingest messages <ingest_data>` into your Graylog and extract the messages with :ref:`extractors <extractors>` or use :ref:`the Pipelines <pipelinestoc>` to work with the mes
I think this should be "The next step is to ingest messages into Graylog and ...".

Same in the other files.

2016-12-10 09:46 UTC, joschi commented on pages/installation/os/debian.rst
> +  $ sudo apt-get update && apt-get upgrade
Either remove `sudo` from the first command or add it to the second command, but as it is, it's inconsistent.

2016-12-12 19:17 UTC, bernd approved these changes

2016-12-12 19:17 UTC, merged