updated wordings and mongodb warning
Graylog2/documentation pull request #242
Opened 2017-01-12 15:28 UTC by jalogisch

start to update wordings and links in the documentation

2017-01-12 15:30 UTC, jalogisch commented
the commits would need to be merged to 2.2 too

2017-01-13 14:00 UTC, bernd requested changes

2017-01-13 14:00 UTC, bernd commented on pages/installation/virtual_machine_appliances.rst
> +credentials if you plan to go into some kind of production with the appliance.
How about removing the last part and just leave the sentence at

> You should change those credentials!

The "some kind of production" doesn't make much sense to me.

2017-01-13 14:02 UTC, jalogisch commented on pages/installation/virtual_machine_appliances.rst
> +credentials if you plan to go into some kind of production with the appliance.
👍

2017-01-13 14:11 UTC, bernd approved these changes

2017-01-13 14:12 UTC, merged