reworked getting started
Graylog2/documentation pull request #274
Opened 2017-02-03 15:53 UTC by jalogisch

I just noticed that getting started was not usable.

people get lost if they follow the steps and so I just updated this to be more useful, additional added the new screenshots and new information and some references.

2017-02-04 12:38 UTC, joschi requested changes

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/check_messages.rst
> +After that, you should can select the *System > Input* page again.
TooManyWordsException("you should can select")

Suggestion: After that, go back to the System / Inputs page.

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/check_messages.rst
> +Click *Show received messages* button for the *appliance-syslog-udp* input, and you should have messages at the bottom. It may take a few minutes before you have messages coming in.
```
Click on the "Show received messages" button next to the *appliance-syslog-udp* input and you should see only the messages received from your syslog clients.
```

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/create_dashboard.rst
> +We will now add a new dashboard, go to *Dashboards* in the top, select *Create dashboard*
```
Now we'll create a new dashboard for these messages by opening the *Dashboards* page in the top menu and clicking on *Create dashboard*.
```

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/create_dashboard.rst
>  Give your new dashboard a title and description.
Maybe suggest a name and a description so it can be referenced later.

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/create_dashboard.rst
> +We'll start by adding the message count data to a dashboard. Click *Add count to dashboard*, and select the new created Dasboard.
```
We'll start by adding a widget with the message count: Click on *Add count to dashboard* and select the $NAME_OF_DASHBOARD dashboard.
```

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/create_dashboard.rst
> +To select only the messages coming in via Syslog go to *System > Inputs*, select the *appliance-syslog-udp* input, and hit Show messages.
```
Click the "Show received messages" button next to the *appliance-syslog-udp* input on the System / Inputs page to only show messages received by this input.
```

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/web_console.rst
> +You can dismiss the Guide, and just follow all steps in this section to get started with Graylog. After that the following screen will be present to you.
Which following screen? There's no screenshot.

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/rsyslog.rst
> +Sending additional Messages
"Sending additional message"

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/rsyslog.rst
> +Sending additional Messages
Maybe "Ingesting more log messages" would be better?

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/rsyslog.rst
> +You can find out more on this in our `Guide to send Syslog over to Graylog <https://github.com/Graylog2/graylog-guide-syslog-linux>`__.
```
"You can find out more about ingesting syslog messages with Graylog in our `Syslog configuration guide <https://github.com/Graylog2/graylog-guide-syslog-linux>`__."
```

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/rsyslog.rst
> +We have even more information how to send messages to Graylog on :ref:`a separate page <ingest_data>`. Use this Page as a start to have more external Data in Graylog.
```
"Please refer to :ref:ingest_data for further instructions about configuring Graylog and ingesting data from external sources."
```

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/rsyslog.rst
> +We’re going to use rsyslog because we already have it running on the showcase. So, go to the image and login with ``ubuntu/ubuntu``.
What's the "showcase"?

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/import_run.rst
> +The above steps are also covered in our :ref:`virtual machine appliance installation page <virtual-machine-appliances>` with some additional information. If you do not have DHCP enabled in your Netwo
"Network" &rarr; "network"

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/explore_graylog.rst
> +By default the appliance is already getting logs. This are the Logfiles from all components that are running inside. This can be disabled later with the :ref:`graylog-ctl`.
```
By default the appliance is already indexing log messages from all components running inside the virtual machine. If you don't want to record these messages, you can disable this internal logging using :ref:`graylog-ctl`.
```

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/explore_graylog.rst
> +If you choose *Streams* on the top you will get a overview of of the pre-defined Streams. Think of them like a pre-sorted view on the incoming messages. Your can find more information on the :ref:`st
```
When opening the *Streams* page in the top menu, you will see a list of all predefined streams. Think of them as a filtered view of all incoming messages.

You can find more information on the :ref:`streams page <streams>`. As you can see, you can define rules for the messages which should be visible in this stream.
```

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/explore_graylog.rst
> +If you choose *Sources* in the Top you will get a nice overview who is sending what amount of Data into your Graylog Setup. In the showcase Setup you only have the graylog-server and nginx visible. I
```
If you click on *Sources* in the top menu, you will see a nice overview of which clients are sending data into Graylog and how much.

In the showcase setup, you will see "graylog-server" and "nginx" in the beginning. Once you start sending data from other systems, their hostnames or IP addresses will be listed on the *Sources* page.
```

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/explore_graylog.rst
> +The most importand part, how does the data actually come into Graylog. Check *System > Inputs* and you will see what is by default enabled. You can already use the running virtual machine as a syslog
```
The most important question is: How will the data actually come into Graylog.

Open the *System > Inputs* page from the top menu and you will see some inputs which are running by default, such as a syslog input.

This means that you can already use the running appliance as a syslog receiver for any device supporting the syslog protocol which is able to connect to the virtual machine on port 514/udp (which happens to be the standard port for syslog).
```

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/explore_graylog.rst
> +If you like to know what options you have to ingest messages to Graylog, look at the page :ref:`ingest_data`.
```
If you would like to know the supported options for ingesting messages into Graylog, you can find additional information at :ref:`ingest_data`.
```

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/explore_graylog.rst
> +In the showcase setup UDP port 514 is already waiting to get some messages.
Remove that sentence in favor of the text two paragraphs before.

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/explore_graylog.rst
> +In the Showcase we have already created a Dashboard for you, just to show what is possible with Graylog. Navigate to *Dasboards* at the top navigation and choose *nginx overview*. After this you will
```
To show what's possible with Graylog, we have already created a few dashboards for you in the virtual appliance.

Navigate to the *Dasboards* page in the top menu and click on *nginx overview*. After this you will see the following screen with a dashboard generated from the internal log data of the virtual appliance itself.
```

2017-02-04 12:38 UTC, joschi commented on pages/getting_started/explore_graylog.rst
> +To have some more data, we will add the Syslog Data from the running virtual machine in the next step.
I'm not sure what this sentence means. We're already collecting syslog messages from the running virtual machine, aren't we?

2017-02-06 09:03 UTC, jalogisch commented on pages/getting_started/explore_graylog.rst
> +To have some more data, we will add the Syslog Data from the running virtual machine in the next step.
nope we are not.

2017-02-06 09:20 UTC, joschi commented on pages/getting_started/explore_graylog.rst
> +To have some more data, we will add the Syslog Data from the running virtual machine in the next step.
The what's the "appliance-syslog-udp" input for?
https://github.com/Graylog2/omnibus-graylog2/blob/2.1.3-1/files/data/contentpacks/content_pack_appliance.json#L6-L24

2017-02-06 10:08 UTC, jalogisch commented on pages/getting_started/explore_graylog.rst
> +To have some more data, we will add the Syslog Data from the running virtual machine in the next step.
but configuration is missing for rsyslog in the appliance to do that. 

triple checked now.

2017-02-06 10:41 UTC, joschi commented on pages/getting_started/explore_graylog.rst
> +To have some more data, we will add the Syslog Data from the running virtual machine in the next step.
✅

2017-02-06 10:42 UTC, joschi commented on pages/getting_started/explore_graylog.rst
> +To have some more data, we will add the Syslog Data from the running virtual machine in the next step.
I'd suggest the following:
"In order to ingest even more data to play around with, we'll show you how to ingest the system logs of the virtual machine running Graylog in the next step."

2017-02-06 10:44 UTC, jalogisch commented on pages/getting_started/create_dashboard.rst
>  Give your new dashboard a title and description.
Should additional to the image be a name written?

In all images is the same name used, but I didn't write it down as I think that this should be something the Person who use this to get a first overview on Graylog should decide.

2017-02-06 10:45 UTC, joschi commented on pages/getting_started/create_dashboard.rst
>  Give your new dashboard a title and description.
People using this guide usually don't want to decide anything. It's kind of a playbook after all. 😉

2017-02-06 10:54 UTC, jalogisch commented on pages/getting_started/create_dashboard.rst
>  Give your new dashboard a title and description.
than IMHO they just need to read what is visible in the picture. 

Add this if you think this is needed, I didn't see a reason for this.

2017-02-06 11:23 UTC, joschi commented on pages/getting_started/create_dashboard.rst
>  Give your new dashboard a title and description.
You can't use the ReadTheDocs search or the browser's in-page search on text in a picture.

2017-02-06 14:30 UTC, jalogisch commented on pages/getting_started/create_dashboard.rst
>  Give your new dashboard a title and description.
added just a description to the image

2017-02-06 14:31 UTC, jalogisch commented
just forget that this is the update I had in mind re-opening #265

2017-02-06 17:02 UTC, joschi requested changes

2017-02-06 17:02 UTC, joschi commented on pages/getting_started/check_messages.rst
> +After that go back to  the *System > Input* page.
```
*System > Inputs*
```

2017-02-06 17:02 UTC, joschi commented on pages/getting_started/create_dashboard.rst
> +Click the "Show received messages" button next to the *appliance-syslog-udp* input on the System / Inputs page to only show messages received by this input.
The reference to the inputs page should be in the same style as the other occurrences:
```
*System > Inputs*
```

2017-02-06 17:02 UTC, joschi commented on pages/getting_started/rsyslog.rst
> +We’re going to use rsyslog because we already have it running on the virtual server. So, go to the image and login with ``ubuntu/ubuntu``.
Why "virtual server" and not "virtual machine" or "appliance"?

2017-02-07 07:46 UTC, joschi approved these changes

2017-02-07 07:47 UTC, merged