Spelling
Graylog2/documentation pull request #306
Opened 2017-05-11 03:34 UTC by jsoref

2017-05-11 07:34 UTC, joschi requested changes
@jsoref Thanks for your contribution to Graylog!

There are a few things to address in this PR before we can merge it.

2017-05-11 07:34 UTC, joschi commented on pages/configuration/https.rst
> +  Organization Name (eg, company) [Internet Widgets Pty Ltd]:Graylog, Inc.
This is actually "correct", as it's the default in OpenSSL:
https://github.com/openssl/openssl/blob/OpenSSL_1_1_0d/apps/openssl.cnf#L139

2017-05-11 07:34 UTC, joschi commented on pages/queries.rst
> +  source:example.org~
This was intentionally spelled wrong to demonstrate fuzzy searches.

2017-05-11 07:34 UTC, joschi commented on pages/queries.rst
> +  source:example.org~1
This was intentionally spelled wrong to demonstrate fuzzy searches.

2017-05-11 14:51 UTC, jsoref commented on pages/configuration/https.rst
> +  Organization Name (eg, company) [Internet Widgets Pty Ltd]:Graylog, Inc.
Ah. Right. I've been meaning to clean that project up... Maybe next week...

2017-05-11 14:54 UTC, jsoref commented on pages/queries.rst
> +  source:example.org~
Would you be ok w/ including ("example is intentionally misspelled below") or something?
(That wouldn't be a change I'd make in this PR, I will drop these two commits when I'm next at my personal workstation.)

2017-05-11 14:55 UTC, joschi commented on pages/queries.rst
> +  source:example.org~
Sure, adding an explanation to these search queries would be fine.

2017-05-12 06:20 UTC, joschi approved these changes

2017-05-12 06:21 UTC, merged

2017-05-12 06:21 UTC, joschi commented
@jsoref Thanks!