small corrections in the docs
Graylog2/documentation pull request #327
Opened 2017-07-07 13:00 UTC by jalogisch

just some small corrections for the documentation - changed versions and removed some warning that are not longer neede.

additional added the 2.3 upgrade nodes from the server repo

2017-07-10 06:49 UTC, joschi requested changes

2017-07-10 06:49 UTC, joschi commented on pages/installation.rst
> +.. caution:: Graylog prior 2.3 **does not** work with Elasticsearch 5.x!
```text
Graylog versions prior to 2.3.0 **do not** work with Elasticsearch 5.x
```

2017-07-10 06:49 UTC, joschi commented on pages/securing.rst
> +      - 9200 (tcp)
👍

2017-07-10 06:49 UTC, joschi commented on pages/upgrade/graylog-2.3.rst
> +Please see `our documentation <http://docs.graylog.org/en/latest/pages/upgrade.html>`_
This link could be replace by an internal reference.

2017-07-10 06:49 UTC, joschi commented on pages/upgrade/graylog-2.3.rst
> +In all prior versions, Graylog used the Elasticsearch node client to connect to an Elasticsearch cluster, which was acting as a client-only Elasticsearch node. For compatibility reasons of the used b
The URL should point to a specific version: https://www.elastic.co/guide/en/elasticsearch/guide/5.4/_talking_to_elasticsearch.html

2017-07-11 07:47 UTC, joschi approved these changes

2017-07-11 07:49 UTC, joschi requested changes

2017-07-11 07:49 UTC, joschi commented on pages/upgrade/graylog-2.3.rst
> +.. warn:: The automatic node discovery does not work if Elasticsearch requires authentication, e. g. when using Shield (X-Pack).
The correct admonition is "warning": http://docutils.sourceforge.net/docs/ref/rst/directives.html#warning

2017-07-11 12:53 UTC, jalogisch commented on pages/upgrade/graylog-2.3.rst
> +.. warn:: The automatic node discovery does not work if Elasticsearch requires authentication, e. g. when using Shield (X-Pack).
opas missed that. Just copied it over from the server repo.

will change

2017-07-11 14:11 UTC, joschi approved these changes

2017-07-11 14:12 UTC, merged