added sentence about SELinux
Graylog2/documentation pull request #385
Opened 2017-11-09 14:34 UTC by jalogisch

2017-12-22 13:17 UTC, jalogisch commented
this need to be cherry-picked into 2.4 and 3.0 once merged

2017-12-22 14:03 UTC, kroepke requested changes

2017-12-22 14:03 UTC, kroepke commented on pages/installation/os/centos.rst
> +Having SELinux disabled during installation and enable it later, forces you to check and controll all policy that need to be present for MongoDB, Elasticsearch and Graylog.
I would rewrite the sentence:
"Having SELinux disabled during installation and enabling it later, requires you to manually check the policies for MongoDB, Elasticsearch and Graylog."

2017-12-28 11:16 UTC, kroepke approved these changes

2017-12-28 11:20 UTC, merged