added journal messages
Graylog2/documentation pull request #390
Opened 2017-11-16 11:18 UTC by jalogisch

After feedback from the community ( https://community.graylog.org/t/graylog-uncommited-messages-deleted-from-journal-utilization-is-too-high/3177/6 ) and some Enterprise Customers I added the error message to the FAQ and put some additional information to it.

This might be good become one chapter "troubleshooting" but currently its better to find that error in the documentation than noting. 

ppl do not read the online description of this error!

2017-12-22 13:18 UTC, jalogisch commented
this need to be cherry-picked into 2.4 and 3.0 once merged

2017-12-22 14:57 UTC, kroepke requested changes

2017-12-22 14:57 UTC, kroepke commented on pages/faq.rst
> +What does "Uncommited messages deleted from journal" means?
`means` -> `mean`

2017-12-22 14:57 UTC, kroepke commented on pages/faq.rst
> +What does "Journal utilization is too high" means?
`means` -> `mean`

2017-12-22 14:57 UTC, kroepke commented on pages/faq.rst
> +Most times Graylog is not able to connect to Elasticsearch or the Elasticsearch Cluster is not able to process the ingested messages in time. Add more resources to Elasticsearch or adjust :ref:`the o
`Most times` -> `This can happen when`

2017-12-22 14:57 UTC, kroepke commented on pages/faq.rst
> +Most times Graylog is not able to connect to Elasticsearch or the Elasticsearch Cluster is not able to process the ingested messages in time. Add more resources to Elasticsearch or adjust :ref:`the o
`Most times` -> `This can happen when`

2017-12-28 11:25 UTC, kroepke approved these changes

2017-12-28 11:27 UTC, merged