reworked enterprise install
Graylog2/documentation pull request #399
Opened 2017-12-18 17:01 UTC by jalogisch

since we have some changed details in Graylog 2.4 and the Installation of Enterprise Packages, that is now visible in the documentation.

All License questions are redirecting to graylog.org/enterprise. If the final location for the .tar is choosen that need to be set too.

2017-12-19 12:27 UTC, bernd requested changes

2017-12-19 12:27 UTC, bernd commented on pages/enterprise/setup.rst
> +.. note:: For previous versions of Graylog Enterprise please contact your support representive.
Please change this to:

> For previous versions of Graylog Enterprise please contact our support.

2017-12-19 12:27 UTC, bernd commented on pages/enterprise/setup.rst
> +Once you installed the Graylog Enterprise Plugins you need to optain a License from `the Graylog Enterprise Page <https://www.graylog.org/enterprise/>`_.
Typo: "optain" -> "obtain"

There are some more of this below.

2017-12-19 12:27 UTC, bernd commented on pages/enterprise/setup.rst
> +Since Graylog 2.4 the Graylog Enterprise Plugins can be installed the same way Graylog is installed. In most setups this will be done with the package tool provided by the distribution you are using
Please downcase `Plugins` to `plugins` everywhere in this document.

2017-12-19 12:27 UTC, bernd commented on pages/enterprise/setup.rst
> +Once you installed the Graylog Enterprise Plugins you need to optain a License from `the Graylog Enterprise Page <https://www.graylog.org/enterprise/>`_.
Please downcase `License` to `license.`

2017-12-19 12:27 UTC, bernd commented on pages/enterprise/setup.rst
> +Once you installed the Graylog Enterprise Plugins you need to optain a License from `the Graylog Enterprise Page <https://www.graylog.org/enterprise/>`_.
Please change the link text to "the Graylog Enterprise web page".

2017-12-19 12:27 UTC, bernd commented on pages/enterprise/setup.rst
> +Should a simple `apt-get install graylog-enterprise-plugins` or `yum install graylog-enterprise-plugins` not work for you, the following information might help you.
I think we should document the `apt-get` and `yum` install methods a bit more than with one sentence. Maybe just replace the `dpkg -i ` and `rpm -Uvh` sections below with the `apt-get` and `yum` instructions.

Installing the packages via the repository should be the main way of doing it.

2017-12-19 14:03 UTC, jalogisch commented on pages/enterprise/setup.rst
> +.. note:: For previous versions of Graylog Enterprise please contact your support representive.
I just followed the wording in https://github.com/Graylog2/graylog-plugin-license/pull/29

2017-12-19 14:11 UTC, bernd commented on pages/enterprise/setup.rst
> +.. note:: For previous versions of Graylog Enterprise please contact your support representive.
Okay, but then use the exact wording please. :wink: 

"For previous versions of Graylog Enterprise please contact your Graylog account manager."

2017-12-22 13:19 UTC, jalogisch commented
this need to be cherry-picked into 3.0 once merged

2017-12-22 13:54 UTC, kroepke approved these changes
premature lgtm...

2017-12-22 13:56 UTC, kroepke requested changes
Some wording issues

2017-12-22 13:56 UTC, kroepke commented on pages/enterprise/setup.rst
> +The installation on distributions like CentOS or RedHat could be done with *yum* as installation tool from the previous installed online repository.
Is "could" the right word here?
I feel it should either be "should" or "can".

2017-12-22 13:56 UTC, kroepke commented on pages/enterprise/setup.rst
> +The installation on distributions like Debian or Ubuntu could be done with *apt-get* as installation tool from the previous installed online repository.
Same as below about "could".

2017-12-28 11:46 UTC, kroepke approved these changes

2017-12-28 11:46 UTC, merged

2017-12-28 11:58 UTC, kroepke commented
957d1d5 is the same change, but with 3.0 package names