Add script alert notification documentation
Graylog2/documentation pull request #540
Opened 2019-01-24 22:52 UTC by cobaltclaudia

Documentation for Script Alert Notification.

2019-01-29 17:39 UTC, danotorrey requested changes
Fantastic job on putting this documentation together. 😃 Looks excellent. 

I only saw a couple of little things that I think we should address (adding `enterprise-integrations` download links, and using "Script Alert Notification" for consistency for now).

I am happy to help if you have any questions or feedback on these.

2019-01-29 17:39 UTC, danotorrey commented on conf.py
> +    'integrations-plugin-rpm': ( 'https://downloads.graylog.org/releases/graylog-integrations/rpm/graylog-plugin-integrations-%s-1.noarch.rpm', None), }
Please include links both for `enterprise-integrations` and `integrations` here. This will allow the user to download the DEB, RPM, or JAR for each.

Like this:

```suggestion
    'integrations-plugin-rpm': ( 'https://downloads.graylog.org/releases/graylog-integrations/rpm/graylog-plugin-integrations-%s-1.noarch.rpm', None),
    'enterprise-integrations-plugin-jar': ( 'https://downloads.graylog.org/releases/graylog-integrations/jar/graylog-plugin-enterprise-integrations-%s.jar', None),
    'enterprise-integrations-plugin-deb': ( 'https://downloads.graylog.org/releases/graylog-integrations/deb/graylog-plugin-enterprise-integrations-%s.deb', None),
    'enterprise-integrations-plugin-rpm': ( 'https://downloads.graylog.org/releases/graylog-integrations/rpm/graylog-plugin-enterprise-integrations-%s-1.noarch.rpm', None), }
```

2019-01-29 17:39 UTC, danotorrey commented on pages/integrations/setup.rst
> +* :integrations-plugin-jar:`3.0.0`
Please also include the `enterprise-integrations` links here too.

```suggestion
* :integrations-plugin-jar:`3.0.0`
* :enterprise-integrations-plugin-deb:`3.0.0`
* :enterprise-integrations-plugin-rpm:`3.0.0`
* :enterprise-integrations-plugin-jar:`3.0.0`
```

2019-01-29 17:39 UTC, danotorrey commented on pages/streams/alerts.rst
> +The Script alert notification lets you configure a script that will be executed when the alert is triggered.
I think we should use capital case for Script Alert Notification here. 
```suggestion
The Script Alert Notification lets you configure a script that will be executed when the alert is triggered.
```

2019-01-29 17:39 UTC, danotorrey commented on pages/streams/alerts.rst
> +    Script Alert Callback success is determined by its exit value; success equals zero.
I think we should change Callback > Notification here for consistency.
```suggestion
    Script Alert Notification success is determined by its exit value; success equals zero.
```

2019-01-29 17:39 UTC, danotorrey commented on pages/configuration/server.conf.rst
> +Script alert callback
I think we should change callback > notification here for consistency.
```suggestion
Script alert notification
```

2019-01-30 15:11 UTC, jalogisch commented
could we possible move the "main" page from `integrations/integrations.html` back to `integrations.html`.

- this will not break the flow when someone is switching between the versions (2.5 to 3.0)
- this will make a cleaner URL structure (IMHO)

2019-01-30 21:38 UTC, danotorrey approved these changes

2019-01-31 08:33 UTC, jalogisch requested changes
I Like that you included a working example.

2019-01-31 08:33 UTC, jalogisch commented on pages/integrations/setup.rst
> +You can also download the JAR plugin files from the `Graylog Downloads <https://www.graylog.org/downloads>`_ page.
is there a reason to not include the tar for the integrations in this? 

Currently, no integrations jar files are given on the download page ...

2019-01-31 08:33 UTC, jalogisch commented on pages/streams/alerts.rst
> +
pls remove the not needed new lines

2019-01-31 08:33 UTC, jalogisch commented on pages/streams/alerts.rst
> +
pls remove the not needed new lines

2019-01-31 08:33 UTC, jalogisch commented on pages/streams/alerts.rst
> +
pls remove the not needed new lines

2019-01-31 21:32 UTC, danotorrey commented on pages/integrations/setup.rst
> +You can also download the JAR plugin files from the `Graylog Downloads <https://www.graylog.org/downloads>`_ page.
@jalogisch Thanks for checking this. We are planning to add download links on the website Downloads page for integrations tarballs. We're planning to discuss this with Lennart. The main goals are:

1) Provide one place where download links are maintained. 
2) Avoid duplication of links in the docs.
3) Eliminate the need to update download links in two places (docs + website). This way we'll just have the links on the website.

Please let us know if you have any concerns.

2019-01-31 21:50 UTC, danotorrey commented
@jalogisch This is ready for your review again. Please note the additional commit, which improved the permitted script path explanation: https://github.com/Graylog2/documentation/pull/540/commits/487e746a99304b46ab4e5a1e14bc71fbb8b52936

2019-02-01 14:41 UTC, jalogisch commented on pages/integrations/setup.rst
> +You can also download the JAR plugin files from the `Graylog Downloads <https://www.graylog.org/downloads>`_ page.
I see the point - but not having an option to download the .jar is a bad situation. 

I agree that we should not have multiple locations - but unless we do not have that on the website, we should have it in the docs IMHO - but your decision.

2019-02-04 08:32 UTC, jalogisch approved these changes
I left just one idea that would make it easier for the customer - but no need to change on that.

2019-02-04 08:32 UTC, jalogisch commented on pages/configuration/file_location.rst
> +.. _scripts_dir:
Did you add the Scripts also to other installation methods or only this single location?

2019-02-04 08:32 UTC, jalogisch commented on pages/configuration/server.conf.rst
> +* ``web_interface_url = https://graylog.example.com``
wouldn't it be better if that is by default `http_external_uri`?

With that, this setting is only needed if this should be different from the default that is already configured. (just as Idea)

2019-02-04 19:18 UTC, danotorrey commented
@jalogisch We talked to @lennartkoopmann and confirmed that he's OK with referring users from docs to Download page for tar/jar download. We will be coordinating with Alyssa over the coming days to put the plan together to get them added at release time.

I made the change to the Enterprise Setup page to refer the user to the Downloads page (https://github.com/Graylog2/documentation/pull/540/commits/66aeffe80b661b298141a951373a6ba8df5e6357).

I think this covers all the changes we wanted to make for Script Alert. PR is ready for your final review and merge if all looks good.

2019-02-04 19:21 UTC, danotorrey commented
@jalogisch Thanks for the note about `web_interface_url`. I talked to Dennis and Bernd, and I believe there is some reason to keep it different. For now, we have added the `integrations_` prefix to keep them unique for integrations.

2019-02-05 11:24 UTC, merged