Update Sidecar documentation to 1.0
Graylog2/documentation pull request #551
Opened 2019-02-06 16:06 UTC by mpfz0r

- Note about Sidecar vs. Collectors (legacy)
- Describe new sidecar.yml
- Update step-by-step guide

2019-02-06 16:44 UTC, jalogisch requested changes
Some rewordings and thoughts

2019-02-06 16:44 UTC, jalogisch commented on pages/sidecar.rst
> +.. _graylog-sidecar:
Did you checked the documentation if this old :Ref: is used somewhere?

2019-02-06 16:44 UTC, jalogisch commented on index.rst
> -   pages/collector_sidecar
we should include a `collector_sidecar` page with the `:orphan:` header that gives notice that this is no longer present and a link to the new page.

2019-02-06 16:44 UTC, jalogisch commented on pages/sidecar.rst
>      [Ubuntu 16.04 with Systemd]
maybe ad `Ubuntu 16.04  and later` ? as 16.04 is EOL in April 2019

2019-02-06 16:44 UTC, jalogisch commented on pages/sidecar.rst
> +|                                     | The token is not optional and needs to be configured.                                                               |
> not optional 

Maybe `mandatory` is the better choice? 

People will not notice the `not` and read optional...

2019-02-12 09:19 UTC, jalogisch approved these changes

2019-02-12 10:36 UTC, mariussturm approved these changes

2019-02-12 12:10 UTC, merged