Event notification plugins
Graylog2/documentation pull request #686
Opened 2019-08-19 14:19 UTC by mariussturm

I think we need to add some stuff regarding the frontend as well!

Fixes #681

2019-08-19 14:29 UTC, edmundoa commented
I will add the frontend part, then!

2019-08-19 16:58 UTC, edmundoa requested changes
I found a couple typos, other than that looks good to me.

2019-08-19 16:58 UTC, edmundoa commented on pages/plugins/event_notifications.rst
> +Event Notifications are responsible for sending information about events to external systems, such as sending an email, push notifications, opening tickets, writing to chat systems etc.
```suggestion
Event Notifications are responsible for sending information about events to external systems, such as sending an email, push notifications, opening tickets, writing to chat systems, etc.
```

2019-08-19 16:58 UTC, edmundoa commented on pages/plugins/event_notifications.rst
> +You can use the build-in notifications as full examples one for a `configuration class <https://github.com/Graylog2/graylog2-server/blob/3.1/graylog2-server/src/main/java/org/graylog/events/notificat
```suggestion
You can use the built-in notifications as full examples one for a `configuration class <https://github.com/Graylog2/graylog2-server/blob/3.1/graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfig.java>`_,
```

2019-08-19 16:58 UTC, edmundoa commented on pages/plugins/event_notifications.rst
> +If content-pack support is desired this methode is called to transfer a notification to a content pack entity.
```suggestion
If content-pack support is desired this method is called to transfer a notification to a content pack entity.
```

2019-08-19 16:58 UTC, edmundoa commented on pages/plugins/event_notifications.rst
> +There is just a single methode to override. The notification logic goes into ``execute(EventNotificationContext ctx)``.
```suggestion
There is just a single method to override. The notification logic goes into ``execute(EventNotificationContext ctx)``.
```

2019-08-21 12:34 UTC, jalogisch approved these changes
👍

2019-08-22 08:48 UTC, edmundoa approved these changes

2019-08-22 08:48 UTC, merged