Add additional information for ipfix input
Graylog2/documentation pull request #798
Opened 2020-02-07 17:44 UTC by ceruleancee

closes #797

2020-02-07 22:15 UTC, lingpri commented on pages/integrations/inputs/ipfix_input.rst
> +      "data_type": "ABSTRACT DATA TYPE"
Just an FYI, I have a image of all the datatypes , that are coded in the spec. I'm wondering, if we can add the picture in here. 

@ceruleancee @jan : Please let us know your thoughts on , if we can include the picture below.

https://user-images.githubusercontent.com/6947168/72761092-84615980-3ba0-11ea-823d-f8cf5aba95ed.png

2020-02-09 12:53 UTC, jalogisch requested changes

2020-02-09 12:53 UTC, jalogisch commented on pages/integrations/inputs/ipfix_input.rst
> +      "data_type": "ABSTRACT DATA TYPE"
I would remove the not needed whitespace on the picture - but yes, please include that.

2020-02-11 10:58 UTC, ceruleancee commented on pages/integrations/inputs/ipfix_input.rst
> +      "data_type": "ABSTRACT DATA TYPE"
cool, great idea! image has been added. 👍

2020-02-11 14:53 UTC, jalogisch approved these changes
👍

2020-02-11 15:21 UTC, merged

2020-02-11 18:09 UTC, lingpri commented
@ceruleancee , is this a good idea, to include this example below from the community , as an example . may be, state in the documentation, that our current implementation does not support basicList or subTemplatemultiList.

{
        "enterprise_number": 21373,
        "information_elements": [
                {
                        "element_id": 4,
                        "name": "mark",
                        "data_type": "unsigned32"
                },
                {
                        "element_id": 6,
                        "name": "conntrack_id",
                        "data_type": "unsigned32"
                }
        ]
}