make windows non that prominent
Graylog2/documentation pull request #958
Opened 2020-10-02 13:43 UTC by jalogisch

after receiving enough questions how windows installations can be handled this should make it more cleear.

2020-10-02 14:09 UTC, thejoeschmosho approved these changes, later dismissed

2020-10-02 14:12 UTC, jalogisch commented
after merge that needs to be cherrypicked to 4.0 too

2020-10-06 15:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Graylog2/documentation?pullRequest=958) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Graylog2/documentation?pullRequest=958) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jalogisch<br/>:x: asachs01<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Graylog2/documentation?pullRequest=958) it.</sub>

2020-10-06 15:19 UTC, asachs01 requested changes

2020-10-06 15:19 UTC, asachs01 commented on pages/faq.rst
> +Graylog is not supported running on Windows.
```suggestion
Running Graylog on Windows is not supported.
```

2020-10-08 13:34 UTC, asachs01 approved these changes
👍

2020-10-08 13:35 UTC, merged