pr feedback
Graylog2/documentation pull request #987
Opened 2020-11-02 20:59 UTC by lingpri

Addressing PR feedback.

https://github.com/Graylog2/documentation/pull/976/files#r516096010
https://github.com/Graylog2/documentation/pull/976/files#r516229278

2020-11-02 21:17 UTC, waab76 requested changes

2020-11-02 21:17 UTC, waab76 commented on pages/alerts.rst
> -    Image to use as the icon for this message.
Did you mean to delete Icon URL?

2020-11-02 21:17 UTC, waab76 commented on pages/alerts.rst
> +    This is a message template and the data described above will be appended below the alert title, when the notification is sent.
```suggestion
    The message that will be sent to Slack.  The data described above can be used in this template.
```

2020-11-03 16:44 UTC, lingpri commented on pages/alerts.rst
> -    Image to use as the icon for this message.
good catch.

2020-11-03 19:55 UTC, waab76 approved these changes
LGTM

2020-11-03 20:14 UTC, merged